//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приложушечка.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedTest_Entities : DbContext
    {
        private static MedTest_Entities _context;
        public MedTest_Entities()
            : base("name=MedTest_Entities")
        {
        }

        public static MedTest_Entities GetContext()
        {
            if (_context == null)
                _context = new MedTest_Entities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<EmployeeOfRegistration> EmployeeOfRegistration { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<Pacients> Pacients { get; set; }
        public virtual DbSet<Raspis> Raspis { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
