//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приложушечка.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raspis
    {
        public int ID { get; set; }
        public string FIODoc { get; set; }
        public string Room { get; set; }
        public string SpecDoc { get; set; }
        public System.DateTime BEginOf { get; set; }
        public System.DateTime EndOF { get; set; }
    }
}
